### ISSUE TITLE
DragMove 鼠标快速点击同时加拖动时，会复制item自身，并插入在DOM里

### ISSUE THREAD

**Issue by ml-cn** [vcxiaohan/jquery-plugins#1]
[点此查看截图](http://thumbnail0.baidupcs.com/thumbnail/538c19242a54f352e4cbc5c036ad0b13?fid=1729209869-250528-63218500532451&time=1476180000&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-zbdFe0KjqZkXvEbh1uZB5AHZtmk%3d&expires=8h&chkbd=0&chkv=0&dp-logid=6604492858311012094&dp-callid=0&size=c256_u256&quality=90)

**Comment by vcxiaohan** [comment]
bug已修改，可以测试一下

**Comment by ml-cn** [comment]
@vcxiaohan 哥们儿辛苦了^_^~
