### ISSUE TITLE
DragMove使用时拖动交换表格的<tr>元素无效，具体请看图片

### ISSUE THREAD

**Issue by tunblr** [vcxiaohan/jquery-plugins#2]
![image](https://cloud.githubusercontent.com/assets/16937791/19305647/82e8db3c-90a4-11e6-835a-673601f823e5.png)

**Comment by ml-cn** [comment]
这个插件是在被拖拽的容器内部放一个子元素（如demo中的i标签）并覆盖在父容器上来实现拖拽。而在表格布局中<tr>标签中只能放<td>标签，其他元素会在DOM渲染时被强制放到外面去，所以才出现题主所描述的现象，如果你非要用这个插件，可以尝试用<ul>等布局来模拟table效果。
手机打字好累~

**Comment by ml-cn** [comment]
晕 html标签被过滤掉了  分别是 tr  td  ul...

**Comment by tunblr** [comment]
但是mousedown事件触发时被拖动元素的起始位置的问题应该和你说的无关吧
