### ISSUE TITLE
请问jquery.faqrobot.js 开源吗?

### ISSUE THREAD

**Issue by Qbuer** [vcxiaohan/jquery-plugins#5]
抱歉打扰了.
我想要实现聊天框效果,但是没有找到合适的插件.

请问jquery.faqrobot.js 开源吗? 非商用.

**Comment by vcxiaohan** [comment]
jquery.faqrobot.js属于公司产品，不开源的，jquery-plugins文件下面的其他插件都开源的

**Comment by Qbuer** [comment]
好的,谢谢
